variables:
  PYTHON: "C:\\python38\\python.exe"
  NSIS: "C:\\program files (x86)\\nsis\\makensis.exe"

stages:
  - build
  - upload

snapshot32:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - choco install python --version 3.8.7 -y -ForceX86
    - '&$env:PYTHON -V'
    - '&$env:PYTHON -m pip install --upgrade pip'
    - '&$env:PYTHON -m pip install --upgrade -r requirements.txt'
    - '&$env:PYTHON -m pip uninstall enum34 -y'
  stage: build
  interruptible: true
  script:
    # Create html documentation firstly.
    - cd doc
    - '&$env:PYTHON documentation_importer.py'
    - cd ..\src
    - '&$env:PYTHON ..\doc\generator.py'
    - '&$env:PYTHON setup.py build'
    - cd ..
    - mkdir artifacts
    - mv src/dist artifacts/TWBlue
  only:
    - master
  artifacts:
    paths:
      - artifacts
    expire_in: 1 day

snapshot64:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - choco install python --version 3.8.7 -y
    - '&$env:PYTHON -V'
    - '&$env:PYTHON -m pip install --upgrade pip'
    - '&$env:PYTHON -m pip install --upgrade -r requirements.txt'
  stage: build
  interruptible: true
  script:
    # Create html documentation firstly.
    - cd doc
    - '&$env:PYTHON documentation_importer.py'
    - cd ..\src
    - '&$env:PYTHON ..\doc\generator.py'
    - '&$env:PYTHON setup.py build'
    - cd ..
    - mkdir artifacts
    - mv src/dist artifacts/TWBlue64
  only:
    - master
  artifacts:
    paths:
      - artifacts
    expire_in: 1 day
