variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PYTHON: "C:\\python38\\python.exe"
  NSIS: "C:\\program files (x86)\\nsis\\makensis.exe"

stages:
  - build
  - make_installer
  - upload

snapshot32:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - choco install python --version 3.8.7 -y -ForceX86
    - '&$env:PYTHON -V'
    - '&$env:PYTHON -m pip install --upgrade pip'
    - '&$env:PYTHON -m pip install --upgrade -r requirements.txt'
    - '&$env:PYTHON -m pip uninstall enum34 -y'
  stage: build
  interruptible: true
  script:
    # Create html documentation firstly.
    - cd doc
    - '&$env:PYTHON documentation_importer.py'
    - cd ..\src
    - '&$env:PYTHON ..\doc\generator.py'
    - '&$env:PYTHON setup.py build'
    - cd ..
    - mkdir artifacts
    - cd scripts
    - '&$env:PYTHON make_archive.py'
    - cd ..
    - mv src/dist artifacts/TWBlue
    - move src/twblue.zip artifacts/twblue_snapshot_x86.zip
  only:
    - tags
  artifacts:
    paths:
      - artifacts
    expire_in: 1 day

snapshot64:
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - choco install python --version 3.8.7 -y
    - '&$env:PYTHON -V'
    - '&$env:PYTHON -m pip install --upgrade pip'
    - '&$env:PYTHON -m pip install --upgrade -r requirements.txt'
  stage: build
  interruptible: true
  script:
    # Create html documentation firstly.
    - cd doc
    - '&$env:PYTHON documentation_importer.py'
    - cd ..\src
    - '&$env:PYTHON ..\doc\generator.py'
    - '&$env:PYTHON setup.py build'
    - cd ..
    - mkdir artifacts
    - cd scripts
    - '&$env:PYTHON make_archive.py'
    - cd ..
    - mv src/dist artifacts/TWBlue64
    - move src/twblue.zip artifacts/twblue_snapshot_x64.zip
  only:
    - tags
  artifacts:
    paths:
      - artifacts
    expire_in: 1 day

generate_versions:
  stage: make_installer
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - Set-Variable -Name "time" -Value (date -Format "%H:%m")
    - echo ${time}
    - echo "started by ${GITLAB_USER_NAME}"
    - choco install nsis -y -ForceX86
  script:
    - move artifacts/TWBlue scripts/
    - move artifacts/TWBlue64 scripts/
    - cd scripts
    - '&$env:NSIS twblue_snapshot.nsi'
    - move twblue_snapshot_setup.exe ../artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 1 day

upload:
  stage: upload
  tags:
    - linux
  image: python
  interruptible: true
  script:
    - cd artifacts
    - python ../scripts/upload.py
  only:
    - next-gen
    - tags
    - schedules